## Thanks to Cees-Jan Kiewiet: https://blog.wyrihaximus.net/2016/11/running-php-unit-tests-on-windows-using-appveyor-and-chocolatey/
## & https://github.com/joomla-framework/database/blob/2.0-dev/.appveyor.yml

## Versioning pattern
version: '{branch} - Build #{build}'

## Disable unneeded features
build: false
platform:
  - x64
clone_folder: C:\projects\userfrosting
branches:
  except:
    - gh-pages
clone_depth: 2

cache:
  - C:\ProgramData\chocolatey\bin -> .appveyor.yml
  - C:\ProgramData\chocolatey\lib -> .appveyor.yml
  - C:\tools\php -> .appveyor.yml
  #- C:\tools\composer -> .appveyor.yml
  - '%LOCALAPPDATA%\Composer\files -> composer.json'

## Build matrix for lowest and highest possible targets
environment:
  DLLVersion: "5.6.1"
  PHPBuild: "x64"
  VC: "vc15"
  matrix:
  - php_ver_target: 7.1
    DLLVersion: "5.3.0"
    VC: "vc14"
  - php_ver_target: 7.2
    DLLVersion: "5.3.0"
  - php_ver_target: 7.3

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1 # this var relates to caching the php  install
  - SET ANSICON=121x90 (121x90)
services:
  - mssql2014
  - mysql
  - postgresql94
  - iis

## Install PHP and composer, and run the appropriate composer command
install:
    - IF EXIST c:\tools\php (SET PHP=0)
    - ps: >-
        If ($env:php_ver_target -eq "5.6") {
          appveyor-retry cinst --params '""/InstallDir:C:\tools\php""' --ignore-checksums -y --forcex86 php --version ((choco search php --exact --all-versions -r | select-string -pattern $env:php_ver_target | sort { [version]($_ -split '\|' | select -last 1) } -Descending | Select-Object -first 1) -replace '[php|]','')
        } Else {
          appveyor-retry cinst --params '""/InstallDir:C:\tools\php""' --ignore-checksums -y php --version ((choco search php --exact --all-versions -r | select-string -pattern $env:php_ver_target | sort { [version]($_ -split '\|' | select -last 1) } -Descending | Select-Object -first 1) -replace '[php|]','')
        }
    - appveyor-retry cinst -y sqlite
    - cd c:\tools\php
    # Get the MSSQL DLL's
    - ps: >-
        If ($env:PHP -eq "1") {
          If ($env:php_ver_target -eq "5.6") {
            $source = "https://cdn.joomla.org/ci/php-sqlsrv.zip"
            $destination = "c:\tools\php\php-sqlsrv.zip"
            Invoke-WebRequest $source -OutFile $destination
            #appveyor-retry appveyor DownloadFile https://cdn.joomla.org/ci/php-sqlsrv.zip
            7z x php-sqlsrv.zip > $null
            copy SQLSRV\php_sqlsrv_56_nts.dll ext\php_sqlsrv_nts.dll
            copy SQLSRV\php_pdo_sqlsrv_56_nts.dll ext\php_pdo_sqlsrv_nts.dll
            Remove-Item c:\tools\php\* -include .zip
            } Else {
            cd c:\tools\php\ext
            $source = "https://windows.php.net/downloads/pecl/releases/sqlsrv/$($env:DLLVersion)/php_sqlsrv-$($env:DLLVersion)-$($env:php_ver_target)-nts-$($env:VC)-$($env:PHPBuild).zip"
            $destination = "c:\tools\php\ext\php_sqlsrv-$($env:DLLVersion)-$($env:php_ver_target)-nts-$($env:VC)-$($env:PHPBuild).zip"
            Invoke-WebRequest $source -OutFile $destination
            #appveyor-retry appveyor DownloadFile http://windows.php.net/downloads/pecl/releases/sqlsrv/$($env:DLLVersion)/php_sqlsrv-$($env:DLLVersion)-$($env:php_ver_target)-nts-$($env:VC)-$($env:PHPBuild).zip
            7z x -y php_sqlsrv-$($env:DLLVersion)-$($env:php_ver_target)-nts-$($env:VC)-$($env:PHPBuild).zip > $null
            $source = "http://windows.php.net/downloads/pecl/releases/pdo_sqlsrv/$($env:DLLVersion)/php_pdo_sqlsrv-$($env:DLLVersion)-$($env:php_ver_target)-nts-$($env:VC)-$($env:PHPBuild).zip"
            $destination = "c:\tools\php\ext\php_pdo_sqlsrv-$($env:DLLVersion)-$($env:php_ver_target)-nts-$($env:VC)-$($env:PHPBuild).zip"
            Invoke-WebRequest $source -OutFile $destination
            #appveyor-retry appveyor DownloadFile http://windows.php.net/downloads/pecl/releases/pdo_sqlsrv/$($env:DLLVersion)/php_pdo_sqlsrv-$($env:DLLVersion)-$($env:php_ver_target)-nts-$($env:VC)-$($env:PHPBuild).zip
            7z x -y php_pdo_sqlsrv-$($env:DLLVersion)-$($env:php_ver_target)-nts-$($env:VC)-$($env:PHPBuild).zip > $null
            Remove-Item c:\tools\php\ext* -include .zip
            cd c:\tools\php}}
    - IF %PHP%==1 copy php.ini-production php.ini /Y
    - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
    - ps: >-
        If ($env:php_ver_target -eq "5.6") {
          Add-Content php.ini "`nextension=php_sqlsrv_nts.dll"
          Add-Content php.ini "`nextension=php_pdo_sqlsrv_nts.dll"
          Add-Content php.ini "`n"
        } Else {
          Add-Content php.ini "`nextension=php_sqlsrv.dll"
          Add-Content php.ini "`nextension=php_pdo_sqlsrv.dll"
          Add-Content php.ini "`n"
        }
    - IF %PHP%==1 echo extension=php_pgsql.dll >> php.ini
    - IF %PHP%==1 echo extension=php_pdo_pgsql.dll >> php.ini
    - IF %PHP%==1 echo extension=php_pdo_sqlite.dll >> php.ini
    - IF %PHP%==1 echo extension=php_sqlite3.dll >> php.ini
    - IF %PHP%==1 echo extension=php_pdo_mysql.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mysqli.dll >> php.ini
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
    - cd c:\projects\database
    - appveyor-retry composer install --no-progress --profile

before_test:
#  Database setup for mysql via PowerShell tools
  - >
    "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -u root -p"Password12!" -e "CREATE DATABASE IF NOT EXISTS userfrosting;"
  - >
    "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -u root -p"Password12!" userfrosting < Tests\Stubs\mysql.sql
#  Database setup for postgreSQL
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.4\bin\;%PATH%
  - createdb userfrosting
  - psql -d userfrosting -a -f Tests\Stubs\postgresql.sql
# Database setup for MSSQL
  - ps: $sqlInstance = "(local)\SQL2014"
  - ps: sqlcmd -b -E -S "$sqlInstance" -Q "CREATE DATABASE userfrosting"
  - ps: sqlcmd -S "$sqlInstance" -U "sa" -P "Password12!" -i $env:APPVEYOR_BUILD_FOLDER\Tests\Stubs\sqlsrv.sql

# Copy sprinkle file
  - cd C:\projects\userfrosting
  - echo F | xcopy app\sprinkles.example.json app\sprinkles.json /y

# Setup .env
  - echo UF_MODE="debug" > app/.env
  - echo DB_DRIVER="sqlsrv" >> app/.env
  - echo DB_HOST=(local)\SQL2014 >> app/.env
  - echo DB_PORT="1433" >> app/.env
  - echo DB_NAME="userfrosting" >> app/.env
  - echo DB_USER="sa" >> app/.env
  - echo DB_PASSWORD="Password12!" >> app/.env
  - echo TEST_DB="default" >> app/.env

# Setup UserFrosting
  - php bakery debug
  - php bakery build-assets
  - php bakery migrate

## Run the actual test
test_script:
  - cd C:\projects\userfrosting
  - app\vendor\bin\phpunit
